ConspiracaoFilmes/ConspiracaoFilmes.Apresentacao/Controllers/BaseController.cs
using ConspiracaoFilmes.Domain.Commons.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ConspiracaoFilmes.Apresentacao.Controllers
{
    public class BaseController : Controller
    {
    public JsonResult ResponseServerStatus(ServerStatus ss)
    {
        return Json(new { status = ss.status, mensagem = ss.mensagem}, JsonRequestBehavior.AllowGet);
    }

}
}

ConspiracaoFilmes/ConspiracaoFilmes.Apresentacao/Controllers/ClienteController.cs
using ConspiracaoFilmes.Application.Interface;
using ConspiracaoFilmes.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using ConspiracaoFilmes.Domain.Commons.Helpers;
using ConspiracaoFilmes.Domain.Commons.Enums;
using ConspiracaoFilmes.Application.Models;

namespace ConspiracaoFilmes.Apresentacao.Controllers
{
    public class ClienteController : BaseController
    {
        private readonly IAppServiceCliente _appService;
        public ClienteController(IAppServiceCliente appService)
        {
            _appService = appService;
        }
        // GET: Cliente

        public ActionResult Create()
        {
            return PartialView(new ClienteModel());
        }


        public ActionResult Edit(int id)
        {
            ClienteModel model = AutoMapper.Mapper.Map<Cliente, ClienteModel>(_appService.GetById(id));
            return PartialView(model);
        }


        public ActionResult GetClientes()
        {
            List<ClienteModel> retorno = AutoMapper.Mapper.Map<List<Cliente>, List<ClienteModel>>(_appService.GetAll().ToList());
        
            return Json(retorno, JsonRequestBehavior.AllowGet);
        }
        //public ActionResult GetClientes()
        //{
        //    List<ClienteModel> retorno = AutoMapper.Mapper.Map<List<Cliente>, List<ClienteModel>>(_appService.GetAll().ToList());
        //    return PartialView(retorno);
        //}


        [HttpPost]
        public ActionResult Create(ClienteModel model)
        {
            try
            {
                Cliente c = AutoMapper.Mapper.Map<ClienteModel, Cliente>(model);
                _appService.Add(c);
                return ResponseServerStatus(new ServerStatus() { status = StatusMensagem.ok, mensagem = "Cliente adicionado com sucesso" });

            }
            catch (Exception ex)
            {

                return ResponseServerStatus(new ServerStatus() { status = StatusMensagem.erro, mensagem = ex.Message });
            }

        }

        [HttpPost]
        public ActionResult Edit(ClienteModel model)
        { 
            try
            {
                _appService.EditarCliente(model);
                return ResponseServerStatus(new ServerStatus() { status = StatusMensagem.ok, mensagem = "Cliente editado com sucesso" });

            }
            catch (Exception ex)
            {

                return ResponseServerStatus(new ServerStatus() { status = StatusMensagem.erro, mensagem = ex.Message });
            }

        }
        public ActionResult Index()
        {
            return View();
        }
    }
}

ConspiracaoFilmes/ConspiracaoFilmes.Apresentacao/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ConspiracaoFilmes.Apresentacao.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ConspiracaoFilmes/ConspiracaoFilmes.Apresentacao/Controllers/ProdutoController.cs
using ConspiracaoFilmes.Application.Interface;
using ConspiracaoFilmes.Application.Models;
using ConspiracaoFilmes.Domain.Commons.Enums;
using ConspiracaoFilmes.Domain.Commons.Helpers;
using ConspiracaoFilmes.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ConspiracaoFilmes.Apresentacao.Controllers
{
    public class ProdutoController : BaseController
    {
        private readonly IAppServiceProduto _appService;
        public ProdutoController(IAppServiceProduto appService)
        {
            _appService = appService;
        }


        public ActionResult Create()
        {
            return View(new ProdutoModel());
        }

        public ActionResult Edit(int idProduto)
        {
            Produto p = _appService.GetById(idProduto);
            ProdutoModel model = AutoMapper.Mapper.Map<Produto, ProdutoModel>(p);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(ProdutoModel model)
        {
            _appService.AtualizarProduto(model);
            return ResponseServerStatus(new ServerStatus() { status = StatusMensagem.ok, mensagem = "Produto atualizado com sucesso" });
        }

        public ActionResult GetProdutos()
        {
            return PartialView(_appService.GetProdutos());
        }

        [HttpPost]
        public ActionResult Create(ProdutoModel model)
        {
            _appService.AdicionarProduto(model);
            return ResponseServerStatus(new ServerStatus() { status = StatusMensagem.ok, mensagem = "Produto adicionado com sucesso" });

        }
    }
}

ConspiracaoFilmes/ConspiracaoFilmes.Apresentacao/Views/Cliente/Create.cshtml
@model  ConspiracaoFilmes.Application.Models.ClienteModel
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        @using (Html.BeginForm("Create", "Cliente", FormMethod.Post, new { id = "formPostCliente" }))
        {
            <div class="modal-header">
                <div class="modal-title">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <h3><i class="fa fa-save"></i> Adicionar cliente</h3>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-6">
                        @Html.TextBoxFor(x => x.cpfCnpj, new { @class = "form-control", placeholder = "Digite o CPF/CNPJ", required = "required", maxlength = "200" })
                    </div>
                    <div class="col-6">
                        @Html.TextBoxFor(x => x.nome, new { @class = "form-control", placeholder = "Digite o nome", required = "required" })
                    </div>
                </div>
                <br />
            </div>
            <div class="modal-footer">
                <div class="row">
                    <div class="col-12">
                        <button class="btn btn-primary text-right" type="submit">Salvar</button>
                    </div>
                </div>

            </div>
        }
    </div>
</div>
<script src="@Url.Content("~/Scripts/telas/cliente/create.js")"></script>

ConspiracaoFilmes/ConspiracaoFilmes.Apresentacao/Views/Cliente/Edit.cshtml
@model  ConspiracaoFilmes.Application.Models.ClienteModel

<div class="modal-dialog modal-lg">
    <div class="modal-content">
        @using (Html.BeginForm("Edit", "Cliente", FormMethod.Post, new { id = "formEditCliente" }))
        {
            @Html.HiddenFor(x => x.id)
            <div class="modal-header">
                <div class="modal-title">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <h3><i class="fa fa-save"></i> Editar cliente</h3>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-6">
                        @Html.TextBoxFor(x => x.cpfCnpj, new { @class = "form-control", placeholder = "Digite o CPF/CNPJ", required = "required", maxlength = "200", disabled = "disabled" })
                    </div>
                    <div class="col-6">
                        @Html.TextBoxFor(x => x.nome, new { @class = "form-control", placeholder = "Digite o nome", required = "required" })
                    </div>
                </div>
                <br />
            </div>
            <div class="modal-footer">
                <div class="row">
                    <div class="col-12">
                        <button class="btn btn-primary text-right" type="submit">Salvar</button>
                    </div>
                </div>

            </div>
        }
    </div>
</div>
<script src="@Url.Content("~/Scripts/telas/cliente/edit.js")"></script>

ConspiracaoFilmes/ConspiracaoFilmes.Apresentacao/Views/Cliente/GetClientes.cshtml
@model IEnumerable<ConspiracaoFilmes.Application.Models.ClienteModel>

@{
    ViewBag.Title = "GetClientes";
}

<h2>Lista de Clientes</h2>

<br />
<div class="row">
    <div class="col-12">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.nome)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.cpfCnpj)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.dataCadastro)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.cpfCnpj)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.dataCadastro)
                    </td>
                    <td>
                        <button onclick="editCliente(@item.id)" class="btn btn-primary">Editar</button>
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

ConspiracaoFilmes/ConspiracaoFilmes.Apresentacao/Views/Cliente/Index.cshtml
@{
    ViewBag.Title = "Index";

}
<script src="@Url.Content("~/Scripts/Jquery.js")"></script>

<script src="@Url.Content("~/Scripts/telas/cliente/index.js")"></script>


<div class="row">
    <div class="col-12">
        <button onclick="createCliente()" class="btn btn-primary">Adicionar Cliente</button>
        <button onclick="createProduto()" class="btn btn-primary">Adicionar Produto</button>

    </div>
</div>
<div class="row">
    <div class="col-12" id="grid">

    </div>
</div>

ConspiracaoFilmes/ConspiracaoFilmes.Apresentacao/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ConspiracaoFilmes/ConspiracaoFilmes.Apresentacao/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ConspiracaoFilmes/ConspiracaoFilmes.Apresentacao/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ConspiracaoFilmes/ConspiracaoFilmes.Apresentacao/Views/Produto/Create.cshtml
@model  ConspiracaoFilmes.Application.Models.ProdutoModel
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        @using (Html.BeginForm("Create", "Produto", FormMethod.Post, new { id = "formPostProduto" }))
        {
            @Html.HiddenFor(x => x.idCliente)
            <div class="modal-header">
                <div class="modal-title">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <h3><i class="fa fa-save"></i> Adicionar produto</h3>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-body">
                <div class="row">

                    <div class="col-6">
                        <select required class="form-control" id="ddl"></select>
                    </div>
                    <div class="col-6">
                        <select class="form-control" id="tipoPeso">
                            @foreach (var item in (ConspiracaoFilmes.Domain.Commons.Enums.TipoPeso[])Enum.GetValues(typeof(ConspiracaoFilmes.Domain.Commons.Enums.TipoPeso)))
                            {
                                <option value="@item">@item</option>
                            }
                        </select>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-3">
                        @Html.LabelFor(x => x.nome)
                        @Html.TextBoxFor(x => x.nome, new { @class = "form-control", placeholder = "Nome do produto", required = "required" })
                    </div>
                    <div class="col-3">
                        @Html.LabelFor(x => x.quantidade)
                        @Html.TextBoxFor(x => x.quantidade, new { @class = "form-control", placeholder = "Quantidade", type = "number", required = "required" })
                    </div>
                    <div class="col-3">
                        @Html.LabelFor(x => x.peso)
                        @Html.TextBoxFor(x => x.peso, new { @class = "form-control", placeholder = "Peso", type = "text", disabled = "disabled" })
                    </div>
                    <div class="col-3">
                        @Html.LabelFor(x => x.valor)
                        @Html.TextBoxFor(x => x.valor, new { @class = "form-control", placeholder = "Peso", type = "text" })
                    </div>
                </div>
                <br />
            </div>
            <div class="modal-footer">
                <div class="row">
                    <div class="col-12">
                        <button class="btn btn-primary text-right" type="submit">Salvar</button>
                    </div>
                </div>

            </div>
        }
    </div>
</div>
<script src="@Url.Content("~/Scripts/telas/produto/create.js")"></script>

ConspiracaoFilmes/ConspiracaoFilmes.Apresentacao/Views/Produto/Edit.cshtml
@model  ConspiracaoFilmes.Application.Models.ProdutoModel
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        @using (Html.BeginForm("Edit", "Produto", FormMethod.Post, new { id = "formEditProduto" }))
        {
            @Html.HiddenFor(x => x.id)
            <div class="modal-header">
                <div class="modal-title">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <h3><i class="fa fa-save"></i> Editar produto</h3>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-6">
                        <select class="form-control" id="tipoPeso">
                            @foreach (var item in (ConspiracaoFilmes.Domain.Commons.Enums.TipoPeso[])Enum.GetValues(typeof(ConspiracaoFilmes.Domain.Commons.Enums.TipoPeso)))
                            {
                                <option value="@item">@item</option>
                            }
                        </select>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-3">
                        @Html.LabelFor(x => x.nome)
                        @Html.TextBoxFor(x => x.nome, new { @class = "form-control", placeholder = "Nome do produto", required = "required" })
                    </div>
                    <div class="col-3">
                        @Html.LabelFor(x => x.quantidade)
                        @Html.TextBoxFor(x => x.quantidade, new { @class = "form-control", placeholder = "Quantidade", type = "number", required = "required" })
                    </div>
                    <div class="col-3">
                        @Html.LabelFor(x => x.peso)
                        @Html.TextBoxFor(x => x.peso, new { @class = "form-control", placeholder = "Peso", type = "text", disabled = "disabled" })
                    </div>
                    <div class="col-3">
                        @Html.LabelFor(x => x.valor)
                        @Html.TextBoxFor(x => x.valor, new { @class = "form-control", placeholder = "Peso", type = "text" })
                    </div>
                </div>
                <br />
            </div>
            <div class="modal-footer">
                <div class="row">
                    <div class="col-12">
                        <button class="btn btn-primary text-right" type="submit">Salvar</button>
                    </div>
                </div>

            </div>
        }
    </div>
</div>
<script src="@Url.Content("~/Scripts/telas/produto/edit.js")"></script>

ConspiracaoFilmes/ConspiracaoFilmes.Apresentacao/Views/Produto/GetProdutos.cshtml
@model IEnumerable<ConspiracaoFilmes.Application.Models.GridModel>

@{
    ViewBag.Title = "GetProdutos";
}

<h2>GetProdutos</h2>

<table class="table">
    <tr>
        
        <th>
            @Html.DisplayNameFor(model => model.nomeCliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nomeProduto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.quantidade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.peso)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nomeCliente)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nomeProduto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.quantidade)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.peso)
        </td>
        <td>
            <button class="btn btn-info" onclick="editProduto(@item.idProduto)">Editar</button>
        </td>
    </tr>
}

</table>

ConspiracaoFilmes/ConspiracaoFilmes.Apresentacao/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />
</head>
<body>

    <div class="container body-content">
        <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true" id="myModal"></div>

        @RenderBody()
        <hr />

        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>
    <script src="@Url.Content("~/Scripts/Jquery.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/Scripts/main.js")"></script>
    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>